version: "3.4"

services:
  web:
    env_file: .devenv
    image: flaskcondis:latest
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '5000:5000'
networks:
  default:
    external:
      name: condis-dev