version: "3.4"

services:
  db:
    image: datajoint/mysql:5.7
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=simple
    # volumes:
    #   - ./data:/var/lib/mysql
networks:
  default:
    external:
      name: condis-dev