version: "3.4"

services:
  testweb:
    env_file: .testenv
    image: flaskcondis:test
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '5010:5000'
    command: "pytest -p no:cacheprovider -vs condis/tests/test_main.py"
networks:
  default:
    external:
      name: condis-dev