version: "3.4"

services:
  # redis:
  #   image: redis
  #   expose:
  #     - 6379
  web:
    env_file: .env
    image: flaskcondis:latest
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '5000:5000'
  # worker:
  #   image: flaskcondis:latest
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - redis
  #   env_file:
  #     - ".env"
  #   command: ["celery",
  #             "worker",
  #             "-A",
  #             "celery_worker.cel",
  #             "--loglevel=info"]
  # scheduler:
  #   image: flaskcondis:latest
  #   volumes:
  #     - .:/app
  #   command: ["celery",
  #             "beat",
  #             "-A",
  #             "celery_worker.cel",
  #             "--schedule=/tmp/celerybeat-schedule",
  #             "--loglevel=info",
  #             "--pidfile=/tmp/celerybeat.pid"]
  #   depends_on:
  #     - redis
  #     - worker
  #   env_file:
  #     - ".env"
networks:
  default:
    external:
      name: condis-dev